name: Terraform Pipeline

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # Permite iniciar a pipeline manualmente

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar o Terraform CLI
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # Substitua pela versão que você utiliza

      # Passo 3: Configurar as credenciais do GCP
      - name: Configurar credenciais do GCP
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json


      # Passo 4: Inicializar o Terraform
      - name: Inicializar Terraform
        run: terraform init

      # Passo 5: Validar os arquivos Terraform
      - name: Validar arquivos Terraform
        run: terraform validate

      # Passo 6: Verificar formatação dos arquivos
      - name: Verificar formatação (fmt)
        run: terraform fmt -check

      # Passo 7: Gerar o plano Terraform
      - name: Gerar plano Terraform
        run: terraform plan

      # Passo 8: Aplicar mudanças manualmente
      - name: Aplicar mudanças Terraform
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
