name: Terraform Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform_workflow:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permissions for GITHUB_TOKEN
    env: # Environment variables available to all steps in this job
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcp-key.json # Path to the GCP credentials file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.0 # Consider using a .terraform-version file
          terraform_wrapper: true   # Enables features like caching and TF_HTTP_ADDRESS

      - name: Initialize Terraform
        run: terraform init -input=false
        # GOOGLE_APPLICATION_CREDENTIALS and TF_VAR_project_id are inherited from job's env

      - name: Validate Terraform Files
        run: terraform validate
        # GOOGLE_APPLICATION_CREDENTIALS and TF_VAR_project_id are inherited from job's env

      - name: Check Terraform Formatting
        run: terraform fmt -check
        # GOOGLE_APPLICATION_CREDENTIALS and TF_VAR_project_id are inherited from job's env

      - name: Generate Terraform Plan
        run: terraform plan -input=false
        # GOOGLE_APPLICATION_CREDENTIALS and TF_VAR_project_id are inherited from job's env

      - name: Apply Terraform Changes
        if: github.event_name == 'workflow_dispatch' # Changed condition
        run: terraform apply -auto-approve -input=false
        # GOOGLE_APPLICATION_CREDENTIALS and TF_VAR_project_id are inherited from job's env
