name: Terraform Pipeline

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar Terraform
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Passo 3: Configurar credenciais do GCP
      - name: Configurar credenciais do GCP
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $HOME/gcp-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json

      # Passo 4: Inicializar Terraform
      - name: Inicializar Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json

      # Passo 5: Validar arquivos Terraform
      - name: Validar arquivos Terraform
        run: terraform validate
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json

      # Passo 6: Verificar formatação (fmt)
      - name: Verificar formatação dos arquivos
        run: terraform fmt -check
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json

      # Passo 7: Gerar plano Terraform
      - name: Gerar plano Terraform
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json

      # Passo 8: Aplicar mudanças Terraform (opcional, manual)
      - name: Aplicar mudanças Terraform
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
